# Generated by Django 4.2.5 on 2023-09-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="city",
            field=models.CharField(default="Vancouver", max_length=200),
        ),
        migrations.AddField(
            model_name="office",
            name="country",
            field=models.CharField(default="Canada", max_length=200),
        ),
        migrations.AddField(
            model_name="office",
            name="phone_no",
            field=models.CharField(default="6040000000", max_length=200),
        ),
        migrations.AddField(
            model_name="office",
            name="postal_code",
            field=models.CharField(default="VXZ2T1", max_length=200),
        ),
        migrations.AddField(
            model_name="office",
            name="province",
            field=models.CharField(default="BC", max_length=200),
        ),
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.CharField(default="Vancouver", max_length=200),
        ),
        migrations.AddField(
            model_name="organization",
            name="country",
            field=models.CharField(default="Canada", max_length=200),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone_no",
            field=models.CharField(default="6040000000", max_length=200),
        ),
        migrations.AddField(
            model_name="organization",
            name="postal_code",
            field=models.CharField(default="VXZ2T1", max_length=200),
        ),
        migrations.AddField(
            model_name="organization",
            name="province",
            field=models.CharField(default="BC", max_length=200),
        ),
    ]
