# Generated by Django 4.2.5 on 2023-09-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_office_city_office_country_office_phone_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="office",
        ),
        migrations.RemoveField(
            model_name="office",
            name="organization",
        ),
        migrations.AddField(
            model_name="organization",
            name="offices",
            field=models.ManyToManyField(to="organization.office"),
        ),
    ]
