# Generated by Django 4.2.5 on 2023-09-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organization",
            "0003_remove_employee_office_remove_office_organization_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="employees",
            field=models.ManyToManyField(to="organization.employee"),
        ),
    ]
